[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py *_tests.py tests.py
addopts = --strict-markers -v
markers =
    unit: Quick unit tests
    integration: API and database integration tests
